const ELECTRICITY = [
  { code: 'ETH', name: 'Ethiopia', price: 0.006 },
  { code: 'TKM', name: 'Turkmenistan', price: 0.01 },
  { code: 'IRN', name: 'Iran', price: 0.01 },
  { code: 'VEN', name: 'Venezuela', price: 0.01 },
  { code: 'LBY', name: 'Libya', price: 0.02 },
  { code: 'UZB', name: 'Uzbekistan', price: 0.03 },
  { code: 'KGZ', name: 'Kyrgyzstan', price: 0.03 },
  { code: 'TJK', name: 'Tajikistan', price: 0.03 },
  { code: 'QAT', name: 'Qatar', price: 0.03 },
  { code: 'KWT', name: 'Kuwait', price: 0.03 },
  { code: 'OMN', name: 'Oman', price: 0.03 },
  { code: 'CUB', name: 'Cuba', price: 0.03 },
  { code: 'AGO', name: 'Angola', price: 0.03 },
  { code: 'ZMB', name: 'Zambia', price: 0.04 },
  { code: 'EGY', name: 'Egypt', price: 0.04 },
  { code: 'DZA', name: 'Algeria', price: 0.04 },
  { code: 'BHR', name: 'Bahrain', price: 0.04 },
  { code: 'KAZ', name: 'Kazakhstan', price: 0.05 },
  { code: 'BLR', name: 'Belarus', price: 0.05 },
  { code: 'IRQ', name: 'Iraq', price: 0.05 },
  { code: 'SAU', name: 'Saudi Arabia', price: 0.05 },
  { code: 'MYS', name: 'Malaysia', price: 0.05 },
  { code: 'PRY', name: 'Paraguay', price: 0.05 },
  { code: 'BTN', name: 'Bhutan', price: 0.05 },
  { code: 'MMR', name: 'Myanmar', price: 0.05 },
  { code: 'TTO', name: 'Trinidad and Tobago', price: 0.05 },
  { code: 'NGA', name: 'Nigeria', price: 0.06 },
  { code: 'BGD', name: 'Bangladesh', price: 0.06 },
  { code: 'MNG', name: 'Mongolia', price: 0.06 },
  { code: 'SDN', name: 'Sudan', price: 0.06 },
  { code: 'TUR', name: 'Turkey', price: 0.07 },
  { code: 'RUS', name: 'Russia', price: 0.07 },
  { code: 'PAK', name: 'Pakistan', price: 0.07 },
  { code: 'NPL', name: 'Nepal', price: 0.07 },
  { code: 'GEO', name: 'Georgia', price: 0.07 },
  { code: 'AZE', name: 'Azerbaijan', price: 0.07 },
  { code: 'LAO', name: 'Laos', price: 0.07 },
  { code: 'CHN', name: 'China', price: 0.08 },
  { code: 'IND', name: 'India', price: 0.08 },
  { code: 'VNM', name: 'Vietnam', price: 0.08 },
  { code: 'ARG', name: 'Argentina', price: 0.08 },
  { code: 'ARE', name: 'United Arab Emirates', price: 0.08 },
  { code: 'ARM', name: 'Armenia', price: 0.08 },
  { code: 'LKA', name: 'Sri Lanka', price: 0.08 },
  { code: 'SRB', name: 'Serbia', price: 0.09 },
  { code: 'ALB', name: 'Albania', price: 0.09 },
  { code: 'IDN', name: 'Indonesia', price: 0.09 },
  { code: 'TUN', name: 'Tunisia', price: 0.09 },
  { code: 'MOZ', name: 'Mozambique', price: 0.09 },
  { code: 'BOL', name: 'Bolivia', price: 0.09 },
  { code: 'COD', name: 'DR Congo', price: 0.09 },
  { code: 'BIH', name: 'Bosnia and Herzegovina', price: 0.10 },
  { code: 'ECU', name: 'Ecuador', price: 0.10 },
  { code: 'TWN', name: 'Taiwan', price: 0.10 },
  { code: 'TZA', name: 'Tanzania', price: 0.10 },
  { code: 'BWA', name: 'Botswana', price: 0.10 },
  { code: 'LBN', name: 'Lebanon', price: 0.10 },
  { code: 'MKD', name: 'North Macedonia', price: 0.11 },
  { code: 'MNE', name: 'Montenegro', price: 0.10 },
  { code: 'MEX', name: 'Mexico', price: 0.11 },
  { code: 'UKR', name: 'Ukraine', price: 0.11 },
  { code: 'JOR', name: 'Jordan', price: 0.11 },
  { code: 'ZWE', name: 'Zimbabwe', price: 0.11 },
  { code: 'HUN', name: 'Hungary', price: 0.12 },
  { code: 'CAN', name: 'Canada', price: 0.12 },
  { code: 'THA', name: 'Thailand', price: 0.12 },
  { code: 'GHA', name: 'Ghana', price: 0.12 },
  { code: 'MAR', name: 'Morocco', price: 0.13 },
  { code: 'BGR', name: 'Bulgaria', price: 0.13 },
  { code: 'KOR', name: 'South Korea', price: 0.13 },
  { code: 'NAM', name: 'Namibia', price: 0.13 },
  { code: 'NIC', name: 'Nicaragua', price: 0.14 },
  { code: 'CMR', name: 'Cameroon', price: 0.14 },
  { code: 'MDA', name: 'Moldova', price: 0.14 },
  { code: 'CHL', name: 'Chile', price: 0.14 },
  { code: 'ISL', name: 'Iceland', price: 0.14 },
  { code: 'NOR', name: 'Norway', price: 0.15 },
  { code: 'COL', name: 'Colombia', price: 0.15 },
  { code: 'ISR', name: 'Israel', price: 0.15 },
  { code: 'SLV', name: 'El Salvador', price: 0.15 },
  { code: 'CIV', name: 'Ivory Coast', price: 0.15 },
  { code: 'FJI', name: 'Fiji', price: 0.15 },
  { code: 'MLT', name: 'Malta', price: 0.16 },
  { code: 'BRA', name: 'Brazil', price: 0.16 },
  { code: 'PER', name: 'Peru', price: 0.16 },
  { code: 'HRV', name: 'Croatia', price: 0.16 },
  { code: 'ROU', name: 'Romania', price: 0.17 },
  { code: 'CRI', name: 'Costa Rica', price: 0.16 },
  { code: 'HND', name: 'Honduras', price: 0.16 },
  { code: 'GUY', name: 'Guyana', price: 0.16 },
  { code: 'RWA', name: 'Rwanda', price: 0.16 },
  { code: 'DOM', name: 'Dominican Republic', price: 0.17 },
  { code: 'SVN', name: 'Slovenia', price: 0.17 },
  { code: 'USA', name: 'United States', price: 0.18 },
  { code: 'PAN', name: 'Panama', price: 0.19 },
  { code: 'GTM', name: 'Guatemala', price: 0.19 },
  { code: 'PHL', name: 'Philippines', price: 0.19 },
  { code: 'KEN', name: 'Kenya', price: 0.19 },
  { code: 'UGA', name: 'Uganda', price: 0.19 },
  { code: 'HKG', name: 'Hong Kong', price: 0.19 },
  { code: 'ZAF', name: 'South Africa', price: 0.20 },
  { code: 'JPN', name: 'Japan', price: 0.21 },
  { code: 'GRC', name: 'Greece', price: 0.21 },
  { code: 'LTU', name: 'Lithuania', price: 0.22 },
  { code: 'SVK', name: 'Slovakia', price: 0.22 },
  { code: 'LVA', name: 'Latvia', price: 0.23 },
  { code: 'EST', name: 'Estonia', price: 0.23 },
  { code: 'NZL', name: 'New Zealand', price: 0.24 },
  { code: 'URY', name: 'Uruguay', price: 0.24 },
  { code: 'SGP', name: 'Singapore', price: 0.25 },
  { code: 'CYP', name: 'Cyprus', price: 0.25 },
  { code: 'FIN', name: 'Finland', price: 0.26 },
  { code: 'AUS', name: 'Australia', price: 0.26 },
  { code: 'PRT', name: 'Portugal', price: 0.27 },
  { code: 'FRA', name: 'France', price: 0.28 },
  { code: 'ESP', name: 'Spain', price: 0.28 },
  { code: 'SWE', name: 'Sweden', price: 0.28 },
  { code: 'PNG', name: 'Papua New Guinea', price: 0.28 },
  { code: 'HTI', name: 'Haiti', price: 0.28 },
  { code: 'JAM', name: 'Jamaica', price: 0.29 },
  { code: 'NLD', name: 'Netherlands', price: 0.30 },
  { code: 'LUX', name: 'Luxembourg', price: 0.30 },
  { code: 'POL', name: 'Poland', price: 0.30 },
  { code: 'BRB', name: 'Barbados', price: 0.31 },
  { code: 'AUT', name: 'Austria', price: 0.35 },
  { code: 'CZE', name: 'Czech Republic', price: 0.35 },
  { code: 'CYM', name: 'Cayman Islands', price: 0.35 },
  { code: 'DNK', name: 'Denmark', price: 0.36 },
  { code: 'CHE', name: 'Switzerland', price: 0.37 },
  { code: 'GBR', name: 'United Kingdom', price: 0.40 },
  { code: 'BEL', name: 'Belgium', price: 0.40 },
  { code: 'ITA', name: 'Italy', price: 0.41 },
  { code: 'DEU', name: 'Germany', price: 0.41 },
  { code: 'BHS', name: 'Bahamas', price: 0.42 },
  { code: 'IRL', name: 'Ireland', price: 0.45 },
  { code: 'BMU', name: 'Bermuda', price: 0.46 }
];

const US_STATES = [
  { id: 'WA', name: 'Washington', price: 0.11 },
  { id: 'OR', name: 'Oregon', price: 0.13 },
  { id: 'CA', name: 'California', price: 0.32 },
  { id: 'NV', name: 'Nevada', price: 0.14 },
  { id: 'ID', name: 'Idaho', price: 0.09 },
  { id: 'MT', name: 'Montana', price: 0.13 },
  { id: 'WY', name: 'Wyoming', price: 0.11 },
  { id: 'UT', name: 'Utah', price: 0.12 },
  { id: 'AZ', name: 'Arizona', price: 0.15 },
  { id: 'CO', name: 'Colorado', price: 0.14 },
  { id: 'NM', name: 'New Mexico', price: 0.15 },
  { id: 'ND', name: 'North Dakota', price: 0.10 },
  { id: 'SD', name: 'South Dakota', price: 0.12 },
  { id: 'NE', name: 'Nebraska', price: 0.11 },
  { id: 'KS', name: 'Kansas', price: 0.14 },
  { id: 'OK', name: 'Oklahoma', price: 0.11 },
  { id: 'TX', name: 'Texas', price: 0.15 },
  { id: 'MN', name: 'Minnesota', price: 0.14 },
  { id: 'IA', name: 'Iowa', price: 0.12 },
  { id: 'MO', name: 'Missouri', price: 0.12 },
  { id: 'AR', name: 'Arkansas', price: 0.11 },
  { id: 'LA', name: 'Louisiana', price: 0.11 },
  { id: 'WI', name: 'Wisconsin', price: 0.17 },
  { id: 'IL', name: 'Illinois', price: 0.16 },
  { id: 'MI', name: 'Michigan', price: 0.19 },
  { id: 'IN', name: 'Indiana', price: 0.15 },
  { id: 'OH', name: 'Ohio', price: 0.16 },
  { id: 'KY', name: 'Kentucky', price: 0.13 },
  { id: 'TN', name: 'Tennessee', price: 0.13 },
  { id: 'MS', name: 'Mississippi', price: 0.13 },
  { id: 'AL', name: 'Alabama', price: 0.16 },
  { id: 'GA', name: 'Georgia', price: 0.14 },
  { id: 'FL', name: 'Florida', price: 0.16 },
  { id: 'SC', name: 'South Carolina', price: 0.15 },
  { id: 'NC', name: 'North Carolina', price: 0.14 },
  { id: 'VA', name: 'Virginia', price: 0.13 },
  { id: 'WV', name: 'West Virginia', price: 0.13 },
  { id: 'MD', name: 'Maryland', price: 0.17 },
  { id: 'DE', name: 'Delaware', price: 0.15 },
  { id: 'NJ', name: 'New Jersey', price: 0.19 },
  { id: 'PA', name: 'Pennsylvania', price: 0.18 },
  { id: 'NY', name: 'New York', price: 0.25 },
  { id: 'CT', name: 'Connecticut', price: 0.29 },
  { id: 'RI', name: 'Rhode Island', price: 0.24 },
  { id: 'MA', name: 'Massachusetts', price: 0.30 },
  { id: 'VT', name: 'Vermont', price: 0.21 },
  { id: 'NH', name: 'New Hampshire', price: 0.21 },
  { id: 'ME', name: 'Maine', price: 0.18 },
  { id: 'AK', name: 'Alaska', price: 0.24 },
  { id: 'HI', name: 'Hawaii', price: 0.42 }
];

const MAP_VIEWS = ['world', 'usa', 'north america', 'south america', 'europe', 'asia', 'africa', 'oceania'];

const DEVICES = [
  {
    id: 'mini-m4',
    name: 'Mac mini M4 (16 GB)',
    wattsLoad: 38,
    wattsIdle: 4,
    ratePerHour: 0.06,
    hint: 'Ideal provider: tiny idle draw, no battery, quiet.'
  },
  {
    id: 'mini-m4pro',
    name: 'Mac mini M4 Pro (24-64 GB)',
    wattsLoad: 55,
    wattsIdle: 5,
    ratePerHour: 0.07,
    hint: 'More memory = bigger jobs; slightly higher draw.'
  },
  {
    id: 'air-m3',
    name: 'MacBook Air M2/M3/M4',
    wattsLoad: 18,
    wattsIdle: 4,
    ratePerHour: 0.055,
    hint: 'Efficient headless; watch thermals with lid closed.'
  },
  {
    id: 'mbp14',
    name: 'MacBook Pro 14" M4/M4 Pro',
    wattsLoad: 45,
    wattsIdle: 6,
    ratePerHour: 0.075,
    hint: 'Battery wear is the hidden cost if not plugged in 24/7.'
  },
  {
    id: 'mbp16',
    name: 'MacBook Pro 16" M4 Pro/Max',
    wattsLoad: 65,
    wattsIdle: 7,
    ratePerHour: 0.09,
    hint: 'Strong tier; highest laptop draw and heat.'
  },
  {
    id: 'imac-m4',
    name: 'iMac 24" M4',
    wattsLoad: 48,
    wattsIdle: 8,
    ratePerHour: 0.065,
    hint: 'Display adds draw when left on.'
  },
  {
    id: 'studio-max',
    name: 'Mac Studio M4 Max',
    wattsLoad: 80,
    wattsIdle: 12,
    ratePerHour: 0.1,
    hint: 'Pro tier — only worth it if demand for big models holds up.'
  },
  {
    id: 'studio-ultra',
    name: 'Mac Studio M3 Ultra',
    wattsLoad: 120,
    wattsIdle: 18,
    ratePerHour: 0.14,
    hint: 'Top tier; economics depend heavily on sustained utilization.'
  }
];

const DEFAULTS = {
  deviceId: 'mini-m4',
  countryCode: 'USA',
  customPrice: false,
  price: 0.18,
  hours: 24,
  util: 50,
  rate: 0.06,
  hwcost: null,
  view: 'world'
};

const DAYS_PER_MONTH = 30.44;
